version: "3.8"
services:
  # order service
  order-service:
    image: quocbao64/saga-order-service:latest
    ports:
      - "8091:8091"
    restart: on-failure
    depends_on:
      - order-mysql
      - kafka
    environment:
      - spring.datasource.url=jdbc:mysql://order-mysql:3306/orderdb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.kafka.bootstrap-servers=kafka:9092

  order-mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=orderdb
    volumes:
      - order-db:/var/lib/mysql

  # orchestrator service
  orchestrator-service:
    image: quocbao64/saga-orchestrator-service:latest
    restart: no
    ports:
      - "8092:8092"
    depends_on:
      - kafka
    environment:
      - spring.kafka.bootstrap-servers=kafka:9092

  # payment service
  payment-service:
    image: quocbao64/saga-payment-service:latest
    ports:
      - "8094:8094"
    restart: on-failure
    depends_on:
      - payment-postgres
      - kafka
    environment:
      - spring.datasource.url=jdbc:postgresql://payment-postgres:5432/paymentdb
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.kafka.bootstrap-servers=kafka:9092
  payment-postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=paymentdb
    volumes:
      - payment-pgdata:/var/lib/postgresql/data

  # stock service
  stock-service:
    image: quocbao64/saga-stock-service:latest
    ports:
      - "8093:8093"
    restart: on-failure
    depends_on:
      - stock-postgres
      - kafka
    environment:
      - spring.datasource.url=jdbc:postgresql://stock-postgres:5432/stockdb
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.kafka.bootstrap-servers=kafka:9092
  stock-postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stockdb
    volumes:
      - stock-pgdata:/var/lib/postgresql/data

  # kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka

volumes:
  order-db:
  payment-pgdata:
  stock-pgdata: